# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(471, 820)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color:#ff7c10")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 501, 271))
        self.frame.setStyleSheet("background-color:#ff9bc1")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 10, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 60, 201, 221))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Downloads/12321.png"))
        self.label_2.setObjectName("label_2")
        self.in_cur = QtWidgets.QLineEdit(self.centralwidget)
        self.in_cur.setGeometry(QtCore.QRect(50, 280, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.in_cur.setFont(font)
        self.in_cur.setStyleSheet("background-color:#ff7c10;\n"
"border: 2px solid #ff9bc1;\n"
"border-radius: 30;\n"
"color:#ffffff")
        self.in_cur.setAlignment(QtCore.Qt.AlignCenter)
        self.in_cur.setObjectName("in_cur")
        self.in_am = QtWidgets.QLineEdit(self.centralwidget)
        self.in_am.setGeometry(QtCore.QRect(50, 380, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.in_am.setFont(font)
        self.in_am.setStyleSheet("background-color:#ff7c10;\n"
"border: 2px solid #ff9bc1;\n"
"border-radius: 30;\n"
"color:#ffffff")
        self.in_am.setAlignment(QtCore.Qt.AlignCenter)
        self.in_am.setObjectName("in_am")
        self.out_am = QtWidgets.QLineEdit(self.centralwidget)
        self.out_am.setGeometry(QtCore.QRect(50, 480, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.out_am.setFont(font)
        self.out_am.setStyleSheet("background-color:#ff7c10;\n"
"border: 2px solid #ff9bc1;\n"
"border-radius: 30;\n"
"color:#ffffff")
        self.out_am.setAlignment(QtCore.Qt.AlignCenter)
        self.out_am.setObjectName("out_am")
        self.out_cur = QtWidgets.QLineEdit(self.centralwidget)
        self.out_cur.setGeometry(QtCore.QRect(50, 580, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.out_cur.setFont(font)
        self.out_cur.setStyleSheet("background-color:#ff7c10;\n"
"border: 2px solid #ff9bc1;\n"
"border-radius: 30;\n"
"color:#ffffff")
        self.out_cur.setAlignment(QtCore.Qt.AlignCenter)
        self.out_cur.setObjectName("out_cur")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 750, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{background-color:#ff9bc1;\n"
"border: 2px solid #ff9bc1;\n"
"border-radius: 30;\n"
"color:#ffffff;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#ff9bc1;\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.add_db = QtWidgets.QPushButton(self.centralwidget)
        self.add_db.setGeometry(QtCore.QRect(50, 680, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(14)
        self.add_db.setFont(font)
        self.add_db.setStyleSheet("QPushButton{background-color:#ff9bc1;\n"
"border: 2px solid #ff9bc1;\n"
"border-radius: 30;\n"
"color:#ffffff;\n"
"}\n"
"QPushButton:pressed {\n"
"background-color:#ff9bc1;\n"
"\n"
"}")
        self.add_db.setObjectName("add_db")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Конвертер валют"))
        self.pushButton.setText(_translate("MainWindow", "КОНВЕРТИРОВАТЬ"))
        self.add_db.setText(_translate("MainWindow", "СОХРАНИТЬ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
